### ISSUE TITLE
Internal Bluebird promise is not compatible with es6 Promise interace

### ISSUE THREAD

**Issue by rokoroku** [types/npm-sequelize#78]
#When I tried to make a method that wraps model methods and return with default es6 Promise interface (declared from [lib.es6.d.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts)), it returns incompatible type error: 
```
[ts] Bluebird<Model> is not compatible with Promise<Model>
```

So I changed [promise.d.ts](https://github.com/types/npm-sequelize/blob/master/4/lib/promise.d.ts) file like this
```typescript
import * as Bluebird from 'bluebird';

export const Promise: typeof Bluebird;
// export type Promise<T> = Bluebird<T>;
export default Promise;
```

then the error has gone.

Consider this issue :)

**Comment by felixfbecker** [comment]
I also met this issue before, but what you did cannot be considered a fix. You changed the file so that instead of exporting a Bluebird promise, you are just exporting a plain ES6 Promise. Which means all methods in Sequelize are now typed as returning a plain ES6 promise, and you cannot use any of the bluebird methods on it (like `.finally()` etc).

Can you provide me a bit more details how the error occured? What code caused this, what TS version are you using and what Sequelize version?

**Comment by rokoroku** [comment]
Oh, I know that it's not a fix, It's just workarounds for es6 syntax.

Regenerating the error message is quite easy. See below code:
```typescript

import { Model } from 'sequelize';

export class MyModel extends Model {
  static getSomeModel(): Promise<MyModel[]> {
    return this.findAll({ where: { someProperty: true } });
  }
} 
```
in typescript v2.0.9, sequelize v4.0.0-1

Should we wait for bluebird typings takes es6 Promise compatable interface?

**Comment by felixfbecker** [comment]
@rokoroku https://github.com/types/npm-bluebird/issues/34#issuecomment-260428783
